### ISSUE TITLE
NRF51 bug traceback

### ISSUE THREAD

**Issue by AlexDM0** [crownstone/bluenet#25]
Triggers on 4 times not filling in the bonding keycode correctly:

UART:

```
[cs_main_crownstone.cpp         : 660  ] ---- running ----
[cs_main_crownstone.cpp         : 323  ] onConnect...
[cs_main_crownstone.cpp         : 349  ] onDisconnect...
[cs_Stack.cpp                   : 547  ] Start advertising
[cs_Mesh.cpp                    : 78   ] Failed to restart mesh (8)
[cs_main_crownstone.cpp         : 323  ] onConnect...
[cs_Stack.cpp                   : 812  ] going into low power mode for bonding ...
[cs_Stack.cpp                   : 825  ] bonding failed with error: 129 (0x81)
[cs_main_crownstone.cpp         : 349  ] onDisconnect...
[cs_Stack.cpp                   : 547  ] Start advertising
[cs_Mesh.cpp                    : 78   ] Failed to restart mesh (8)
[cs_main_crownstone.cpp         : 323  ] onConnect...
[cs_Stack.cpp                   : 812  ] going into low power mode for bonding ...
[cs_Stack.cpp                   : 825  ] bonding failed with error: 129 (0x81)
[cs_main_crownstone.cpp         : 349  ] onDisconnect...
[cs_Stack.cpp                   : 547  ] Start advertising
[cs_Mesh.cpp                    : 78   ] Failed to restart mesh (8)
[cs_main_crownstone.cpp         : 323  ] onConnect...
[cs_Stack.cpp                   : 812  ] going into low power mode for bonding ...
[cs_Stack.cpp                   : 825  ] bonding failed with error: 129 (0x81)
[cs_main_crownstone.cpp         : 349  ] onDisconnect...
[cs_Stack.cpp                   : 547  ] Start advertising
[cs_Mesh.cpp                    : 78   ] Failed to restart mesh (8)
[cs_main_crownstone.cpp         : 323  ] onConnect...
[cs_Stack.cpp                   : 812  ] going into low power mode for bonding ...
[cs_BleError.cpp                : 28   ] FATAL ERROR 4, at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/include/drivers/cs_Timer.h:52
```

GDB BT

```
Read 4 bytes @ address 0x200030F0 (Data = 0x00000009)
#1  0x0001f0fa in Timer::createSingleShot (timer_handle=@0x200030f0: 9, func=func@entry=0x1f975 <Nrf51822BluetoothStack::lowPowerTimeout(void*)>, this=<optimized out>)
    at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/include/drivers/cs_Timer.h:52
Read 4 bytes @ address 0x0001FF42 (Data = 0xB5F8BD70)
#2  0x0001f9e0 in Nrf51822BluetoothStack::deviceManagerEvtHandler (this=0x20003080 <Nrf51822BluetoothStack::getInstance()::instance>, p_handle=p_handle@entry=0x20007ed0, 
    p_event=p_event@entry=0x20007ed4, event_result=event_result@entry=0) at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/src/ble/cs_Stack.cpp:815
#3  0x0001ff42 in device_manager_evt_handler (p_handle=0x20007ed0, p_event=0x20007ed4, event_result=0) at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/src/ble/cs_Stack.cpp:758
Read 4 bytes @ address 0x00029F74 (Data = 0x2B127823)
Reading 64 bytes @ address 0x20007F00
#4  0x00029f74 in app_evt_notify (event_result=<optimized out>, p_event=0x20007ed4, p_handle=0x20007ed0)
    at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/src/third/nrf/device_manager_peripheral.c:842
#5  dm_ble_evt_handler (p_ble_evt=<optimized out>) at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/src/third/nrf/device_manager_peripheral.c:2874
Read 4 bytes @ address 0x0001FC2E (Data = 0x2B1B882B)
Reading 64 bytes @ address 0x20007EC0
Read 4 bytes @ address 0x0001FF1A (Data = 0xB510BD10)
#6  0x0001fc2e in Nrf51822BluetoothStack::on_ble_evt (this=0x20003080 <Nrf51822BluetoothStack::getInstance()::instance>, 
    p_ble_evt=p_ble_evt@entry=0x200031b0 <Nrf51822BluetoothStack::init()::BLE_EVT_BUFFER>) at /home/alex/Dropbox/DoBots/Projects/eclipseWorkspace/bluenet/src/ble/cs_Stack.cpp:921
#7  0x0001ff1a in ble_evt_dispatch (p_ble_evt=0x200031b0 <Nrf51822BluetoothStack::init()::BLE_EVT_BUFFER>)
```

**Comment by mrquincle** [comment]
We're using the NRF52 now. Won't fix.
